### ISSUE TITLE
Prelaunch tasks

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_rework#183]
- [x] Rare shows logic implement
- [x] Remove arcsi weekly view and show latest episode link in Schedule
- [x] check footer: text, links, sponsors, collaborators @gammaw 
- [x] @baxgas please remove all sponsors for now
- [x] check Community page content @gammaw ?
- [x] Shows page 4 in a row and more compact (no white back, just title?)

**Comment by gammaw** [comment]
> check footer: text, links, sponsors, collaborators @gammaw

@baxgas it's kind of done I guess. I asked you here https://github.com/mmmnmnm/lahmacun_rework/pull/171 to update the Impressum text on the hyperlink and elsewhere (Trello) that you delete all sponsor logos. Can you do it? 

>  check Community page content @gammaw ?

I need to find 1-2 more pictures but otherwise we're done contentwise. I asked you to modify the template so that the pictures are used from WP. What do you think of it?

**Comment by baxgas** [comment]
@gammaw yes, this is a check list, so we collect all the infos

**Comment by gammaw** [comment]
@baxgas thanks! It's deliberately not a PR yet, right?

**Comment by baxgas** [comment]
@gammaw see the dependencies check-list. 
gygabor's list is a separate task, pvj's is a trello task IMHO. So, you think we should leave them out from here?

**Comment by gammaw** [comment]
Thanks @baxgas for the PR https://github.com/mmmnmnm/lahmacun_rework/pull/184, I'll check it asap.
