### ISSUE TITLE
Fixed height for home page daily schedule component

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun_rework#77]
Regardless of the amount of shows airing on the day the box should be of fixed height.

I am not sure what this means for the show rows -- 

should they re-size depending on the number of shows or should they be fixed w/ only the margins between the schedule box and the row container changing? I don't understand what's better for users so I'll let this to you @baxgas and @gygabor to figure out and strike down 🗡️

**Comment by baxgas** [comment]
@pvj 
The best is Freedom :-) 
Fixed stuff is always problematic, here we might have a Schedule with 15 entries and a News entry with one line of description. So the bigger ones should always give space to smaller ones, but it is a question if it is good to have so much empty space.
Also, I don't think the format of the News image could be sensible in real-world scenarios since most of the times the News are about new Shows in which case the required format is the square picture –> unless we have somebody who makes the graphics and editing of the page, which is the ideal situation, butttt... ... who is da man (or woman) for this?

**Comment by pvj** [comment]
>The best is Freedom :-)

Free as in freedom! As you say.

>Fixed stuff is always problematic

Interesting from my perspective as user: it is always when boxes and containers have different height and my muscle memory fails that I think it would have been better to have things fixed. 

I think of it as a note on a board we always should be able to display the current day's programming w/o making user scroll. But I might change my mind once I see the text size for 15 shows, so this is just me thinking w/o experience to back it up. 

>Also, I don't think the format of the News image could be sensible in real-world scenarios since most of the times the News are about new Shows in which case the required format is the square picture

Good point!
